[2013-07-30 01:38:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php:4945
Stack trace:
#0 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\Dev\workspace\laravelpruebas\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-30 02:25:50] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php:4945
Stack trace:
#0 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\Dev\workspace\laravelpruebas\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-30 02:25:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php:4945
Stack trace:
#0 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\Dev\workspace\laravelpruebas\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-30 02:28:17] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php:4948
Stack trace:
#0 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\Dev\workspace\laravelpruebas\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-30 03:12:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'funtion' (T_STRING), expecting variable (T_VARIABLE)' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:9
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-30 03:13:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php:4945
Stack trace:
#0 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 D:\Dev\workspace\laravelpruebas\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 D:\Dev\workspace\laravelpruebas\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-07-30 03:18:12] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'echo' (T_ECHO)' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-30 03:18:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-30 03:18:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-30 03:19:16] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-30 03:19:20] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-30 03:19:23] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ')'' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:27
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-07-30 03:23:41] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$campo' (T_VARIABLE)' in D:\Dev\workspace\laravelpruebas\app\controllers\PruebaController.php:28
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
